# Generated by Django 3.2 on 2022-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planvisit',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='planvisit',
            old_name='phone_number',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='planvisit',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
