# Generated by Django 3.2 on 2022-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=55, null=True, upload_to='')),
                ('location', models.CharField(max_length=40, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(max_length=55, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, max_length=55, null=True, upload_to=''),
        ),
    ]
