# Generated by Django 3.2 on 2022-09-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_admin', '0004_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
